### ISSUE TITLE
Add additional automation and multi node cluster setup

### ISSUE THREAD

**Issue by cloudartist** [cloudartist/no-cost-multi-cloud-k8s-control-plane#5]
- [ ] Add networking between AWS and Azure
- [ ] Setup hostname as part of user/custom data like _(assuming Azure is created first)_
```
sudo hostname k8s-control-plane-dev.westeurope.cloudapp.azure.com
sudo vi /etc/hostname
sudo vi /etc/hosts
127.0.1.1 k8s-control-plane-dev.westeurope.cloudapp.azure.com
```
- [ ] Automate cluster join _(assuming AWS joins existing cluster)_
```
   kubeadm join k8s-control-plane-dev.westeurope.cloudapp.azure.com:6443 --token xxx \
        --discovery-token-ca-cert-hash sha256:xxx \
        --control-plane
```

**Comment by cloudartist** [comment]
At the moment main problem in establishing multi cloud cluster is `etcd` endpoint is exposed only as a private IP 
```
I1006 18:00:00.510205   16063 etcd.go:166] retrieving etcd endpoints from "kubeadm.kubernetes.io/etcd.advertise-client-urls" annotation in etcd Pods
I1006 18:00:02.231481   16063 etcd.go:102] etcd endpoints read from pods: https://10.0.1.4:2379
context deadline exceeded
error syncing endpoints with etcd
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.NewFromCluster
```
To get working, k8s cluster declarative (instead of imperative) approach need to be taken. Control Plane config would look something like
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v${K8S_VERSION}
clusterName: ${K8S_CLUSTER_NAME}
controlPlaneEndpoint: ${K8S_API_ENDPOINT_INTERNAL}:6443
certificatesDir: ${LOCAL_CERTS_DIR}
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - ${K8S_API_ENDPOINT_INTERNAL}
  - ${K8S_API_ENDPOINT}
etcd:
    external:
        endpoints:
        - https://ETCD_0_IP:2379
        - https://ETCD_1_IP:2379
        - https://ETCD_2_IP:2379
 
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
  extraArgs:
    max-requests-inflight: "1000"
    max-mutating-requests-inflight: "500"        
    default-watch-cache-size: "500"
    watch-cache-sizes: "persistentvolumeclaims#1000,persistentvolumes#1000"

controllerManager:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
  extraArgs:
    deployment-controller-sync-period: "50s"
```
